# Generated by Django 5.0.7 on 2026-05-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keywordresult',
            old_name='demand_score',
            new_name='avg_clicks',
        ),
        migrations.AddField(
            model_name='keywordresult',
            name='avg_ctr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='keywordresult',
            name='avg_searches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='keywordresult',
            name='kd',
            field=models.IntegerField(default=0),
        ),
    ]
