# Generated by Django 5.0.7 on 2026-05-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0002_rename_demand_score_keywordresult_avg_clicks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordresult',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='keywordresult',
            name='avg_ctr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='keywordresult',
            name='kd',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
