# Generated by Django 4.2.30 on 2026-06-05 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('target_regions', models.CharField(default='Global', max_length=255)),
                ('sourcing_days_prior', models.IntegerField(default=90)),
                ('design_days_prior', models.IntegerField(default=60)),
                ('niche_categories', models.JSONField(default=list)),
                ('seo_keywords', models.JSONField(default=list)),
                ('aesthetic_vibe', models.TextField(blank=True, null=True)),
                ('target_buyer_profile', models.TextField(blank=True, null=True)),
                ('is_system_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forecast_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['month', 'day'],
            },
        ),
        migrations.CreateModel(
            name='ForecastTaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='forecaster.forecastevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'event', 'task_name')},
            },
        ),
    ]
